/** Product-scoped regeneration from immutable native paths; never writes IFC. */
import {readFileSync, writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
const root=resolve(import.meta.dir,'../..');
const dir=resolve(root,'output/review/highpoly-types/gessi316-54093');
const read=(p)=>JSON.parse(readFileSync(p,'utf8'));
const save=(p,d)=>writeFileSync(p,JSON.stringify(d,null,2)+'\n');
const hash=(p)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const formal=resolve(root,'2504 GBTB Yanlord Zhuhai.ifc');
const formalHash=hash(formal);
const source=resolve(dir,'official-source/GPF5409300000G000_3.dwg');
if(hash(source)!=='a9308fc8498d34c8cf2f68fd28aaf90b11e62bfc59424e0a5a3ac7f0d28d5047')throw Error('DWG changed');
const manifest=read(resolve(dir,'manifest.json'));
const candidatePath=resolve(dir,'candidate-representations.json');
const candidate=read(candidatePath);
const native=read(resolve(dir,'official-native-dwg-linework.json'));
const old=candidate.views.plan.official_native_dwg_paths_mm;
const minimum=manifest.bounds_mm.minimum;
const centerX=(minimum[0]+manifest.bounds_mm.maximum[0])/2;
const side=candidate.views.side.official_native_dwg_paths_mm;
const sideAxisY=(side[7][0][0]+side[9][0][0])/2;
const nativeAxisY=Math.min(...native.views.plan.paths_mm[4].map(p=>p[1]));
const corrected=native.views.plan.paths_mm.map(path=>path.map(([x,y])=>[+(centerX+x).toFixed(6),+(sideAxisY+nativeAxisY-y).toFixed(6)]));
const svgPath=resolve(dir,'plan.svg');
let svg=readFileSync(svgPath,'utf8');
const tag=svg.match(/<path class="official-reference native-dwg"[^>]*>/)?.[0];
if(!tag)throw Error('Unexpected Plan official SVG class');
const coords=tag.match(/ d="([^"]+)"/)[1].match(/-?\d+(?:\.\d+)?/g).map(Number);
// Reuse the existing plot calibration, keeping gray and black exactly intact.
const sy=(coords[3]-coords[1])/(old[0][1][1]-old[0][0][1]);
const scale=-sy;
const tx=coords[0]-scale*old[0][0][0];
const ty=coords[1]-sy*old[0][0][1];
const d=corrected.map(path=>path.map(([x,y],i)=>`${i?'L':'M'} ${(tx+scale*x).toFixed(3)} ${(ty+sy*y).toFixed(3)}`).join(' ')).join(' ');
svg=svg.replace(/<path class="(?:official-reference-mask|official-reference native-dwg)"[^>]*>/g,t=>t.replace(/ d="[^"]*"/,` d="${d}"`));
writeFileSync(svgPath,svg);
candidate.views.plan.official_native_dwg_paths_mm=corrected;
candidate.views.plan.axis_registration={method:'native_plan_y_reversed_about_semantic_installation_axis',source_native_axis_y_mm:nativeAxisY,target_local_axis_y_mm:sideAxisY,scale:1,not_bbox_only:true};
save(candidatePath,candidate);
// After reflection the arc's maximum, not minimum, is the stem join.
const planStemY=Math.max(...corrected[4].map(p=>p[1]));
const planTipY=Math.max(...corrected.flat().map(p=>p[1]));
const sideTipY=Math.max(...side.flat().map(p=>p[0]));
const report={generated_at:new Date().toISOString(),cause:'Source Plan sheet Y has opposite direction to product local Y; previous bbox-only translation preserved wrong view orientation.',method:'Reflect only native Plan Y and register stem axis to unchanged Side stem axis. Front and Side retained. No scale/stretch.',source_dwg_sha256:hash(source),shared_local_installation_axis_mm:[centerX,sideAxisY],plan_stem_axis_y_mm:planStemY,side_stem_axis_y_mm:sideAxisY,installation_axis_delta_mm:Math.abs(planStemY-sideAxisY),plan_outlet_depth_mm:planTipY,side_outlet_depth_mm:sideTipY,outlet_depth_delta_mm:Math.abs(planTipY-sideTipY),ifc_local_stem_nominal_axis_y_mm:0,official_to_ifc_stem_axis_delta_mm:Math.abs(sideAxisY),residual_note:'Existing envelope registration leaves 0.513 mm nominal stem offset to IFC. It is disclosed, not hidden by independently centering the views. Native Front/Side Z ranges retained.',official_native_path_counts:[7,914,21],formal_ifc_sha256:formalHash,formal_ifc_unchanged:hash(formal)===formalHash,ifc_write:false,review_status:'pending_user_reapproval'};
if(report.installation_axis_delta_mm>0.00001||report.outlet_depth_delta_mm>0.001)throw Error('Shared semantic axis test failed');
save(resolve(dir,'plan-direction-correction-audit.json'),report);
manifest.candidate_representations_sha256=hash(candidatePath);
manifest.project_context.manifest_sha256=hash(resolve(dir,'project-context-manifest.json'));
manifest.views.find(v=>v.view==='plan').svg_sha256=hash(svgPath);
manifest.plan_direction_correction={audit:'output/review/highpoly-types/gessi316-54093/plan-direction-correction-audit.json',status:'corrected_pending_review'};
save(resolve(dir,'manifest.json'),manifest);
const approvalPath=resolve(root,'pipeline/decisions/gessi316-54093-drawing-approval.json');
const approval=read(approvalPath);
approval.candidate_manifest_sha256=hash(resolve(dir,'manifest.json'));
approval.review_stage='plan_direction_corrected_pending_reapproval';
save(approvalPath,approval);
console.log(JSON.stringify(report,null,2));
