#!/usr/bin/env python3
"""Refresh registered plan sources through native Bonsai Drawing operators.

Run this script inside an isolated Blender/Bonsai process. It loads the formal
IFC read-only, redirects each Drawing document to a temporary output, calls
``bim.create_drawing``, validates the generated SVG and linked assets, and
promotes the complete set only after every requested Drawing passes. The
in-memory IFC is never saved.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import struct
import sys
import traceback
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import bpy
import ifcopenshell.util.element
from bonsai import tool

from plan_elevation_index import apply_official_elevation_index


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ELEVATION_INDEX_REGISTER = PROJECT_ROOT / "pipeline/decisions/int1-elevation-view-register.csv"
XLINK_HREF = "{http://www.w3.org/1999/xlink}href"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def png_dimensions(path: Path) -> tuple[int, int]:
    header = path.read_bytes()[:24]
    if len(header) != 24 or header[:8] != b"\x89PNG\r\n\x1a\n":
        raise RuntimeError(f"invalid PNG generated by Bonsai: {path}")
    return struct.unpack(">II", header[16:24])


def parse_args() -> argparse.Namespace:
    arguments = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ifc", type=Path, required=True)
    parser.add_argument("--register", type=Path, required=True)
    parser.add_argument("--candidate-dir", type=Path, required=True)
    parser.add_argument("--drawing", action="append", default=[])
    return parser.parse_args(arguments)


def disable_unrelated_project_handlers() -> list[str]:
    """Remove noisy user-addon handlers from this disposable Blender process."""
    removed: list[str] = []
    for handlers in (
        bpy.app.handlers.depsgraph_update_post,
        bpy.app.handlers.load_post,
        bpy.app.handlers.save_post,
    ):
        for handler in list(handlers):
            module = getattr(handler, "__module__", "")
            if "project_control" not in module:
                continue
            handlers.remove(handler)
            removed.append(f"{module}.{getattr(handler, '__name__', 'handler')}")
    return sorted(set(removed))


def read_register(path: Path, selected: set[str]) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        rows = list(csv.DictReader(handle))
    names = [row["drawing_name"] for row in rows]
    guids = [row["drawing_global_id"] for row in rows]
    if len(names) != len(set(names)) or len(guids) != len(set(guids)):
        raise RuntimeError("Bonsai plan source register has duplicate identity")
    unknown = selected - set(names)
    if unknown:
        raise RuntimeError(f"unknown registered Drawing names: {sorted(unknown)}")
    return [row for row in rows if not selected or row["drawing_name"] in selected]


def linked_materials(image: bpy.types.Image) -> list[str]:
    names: list[str] = []
    for material in bpy.data.materials:
        if not material.use_nodes or not material.node_tree:
            continue
        for node in material.node_tree.nodes:
            if getattr(node, "image", None) != image:
                continue
            if any(socket.links for socket in node.outputs):
                names.append(material.name)
    return sorted(set(names))


def repair_texture_paths() -> tuple[list[str], list[str], list[str]]:
    repaired: list[str] = []
    unresolved_linked: list[str] = []
    unresolved_unlinked: list[str] = []
    for image in bpy.data.images:
        if image.source != "FILE" or not image.filepath:
            continue
        if Path(bpy.path.abspath(image.filepath)).exists():
            continue
        raw = image.filepath.replace("\\", "/")
        candidate = Path("/Users/" + raw.split("/Users/", 1)[1]) if "/Users/" in raw else None
        if candidate and candidate.exists():
            image.filepath = str(candidate)
            image.reload()
            repaired.append(image.name)
            continue
        materials = linked_materials(image)
        target = unresolved_linked if materials else unresolved_unlinked
        target.append(f"{image.name}: {','.join(materials) if materials else 'unused'}")
    return repaired, unresolved_linked, unresolved_unlinked


def drawing_document(model: Any, drawing: Any) -> Any:
    relations = [
        inverse
        for inverse in model.get_inverse(drawing)
        if inverse.is_a("IfcRelAssociatesDocument")
    ]
    if len(relations) != 1:
        raise RuntimeError(f"{drawing.Name}: expected one document relation")
    reference = relations[0].RelatingDocument
    if not reference.is_a("IfcDocumentReference"):
        raise RuntimeError(f"{drawing.Name}: relation is not an IfcDocumentReference")
    return reference


def drawing_operator_context() -> dict[str, Any]:
    for window in bpy.context.window_manager.windows:
        screen = window.screen
        for area in screen.areas:
            if area.type != "VIEW_3D":
                continue
            region = next((item for item in area.regions if item.type == "WINDOW"), None)
            if region:
                return {
                    "window": window,
                    "screen": screen,
                    "area": area,
                    "region": region,
                    "scene": window.scene,
                }
    raise RuntimeError("Blender has no VIEW_3D window context for Bonsai Drawing")


def local_svg_assets(svg_path: Path) -> list[dict[str, Any]]:
    try:
        root = ET.parse(svg_path).getroot()
    except ET.ParseError as exc:
        raise RuntimeError(f"invalid Bonsai SVG: {svg_path}: {exc}") from exc
    hrefs: set[str] = set()
    for node in root.iter():
        href = node.attrib.get(XLINK_HREF) or node.attrib.get("href")
        if not href or href.startswith(("#", "data:", "http://", "https://")):
            continue
        hrefs.add(href)
    assets: list[dict[str, Any]] = []
    for href in sorted(hrefs):
        if Path(href).name != href:
            raise RuntimeError(f"{svg_path.name}: linked asset must be a portable basename: {href}")
        path = svg_path.with_name(href)
        if not path.is_file() or path.stat().st_size == 0:
            raise RuntimeError(f"{svg_path.name}: linked asset is missing: {href}")
        record: dict[str, Any] = {
            "href": href,
            "sha256": sha256(path),
            "bytes": path.stat().st_size,
        }
        if path.suffix.lower() == ".png":
            width, height = png_dimensions(path)
            record["width_px"] = width
            record["height_px"] = height
        assets.append(record)
    return assets


def normalise_svg(path: Path) -> None:
    source = path.read_text(encoding="utf-8")
    normalised = "\n".join(line.rstrip() for line in source.splitlines())
    if source.endswith("\n"):
        normalised += "\n"
    if normalised != source:
        path.write_text(normalised, encoding="utf-8")


def main() -> None:
    args = parse_args()
    os.chdir(PROJECT_ROOT)
    disabled_handlers = disable_unrelated_project_handlers()
    ifc_path = args.ifc.resolve()
    register_path = args.register.resolve()
    candidate_dir = args.candidate_dir.resolve()
    candidate_dir.mkdir(parents=True, exist_ok=True)
    selected = set(args.drawing)
    rows = read_register(register_path, selected)
    if not rows:
        raise RuntimeError("no registered Bonsai plan sources selected")

    formal_hash = sha256(ifc_path)
    result = bpy.ops.bim.load_project(
        filepath=str(ifc_path),
        should_start_fresh_session=True,
        use_detailed_tooltip=True,
    )
    if result != {"FINISHED"} or not tool.Ifc.get():
        raise RuntimeError(f"failed to load formal IFC in Bonsai: {result}")
    if Path(tool.Ifc.get_path()).resolve() != ifc_path:
        raise RuntimeError("Bonsai loaded a different IFC than requested")

    repaired, unresolved_linked, unresolved_unlinked = repair_texture_paths()
    if unresolved_linked:
        raise RuntimeError(f"linked texture images are unresolved: {unresolved_linked}")

    model = tool.Ifc.get()
    reports: list[dict[str, Any]] = []
    original_locations: dict[str, str] = {}
    for row in rows:
        drawing = model.by_guid(row["drawing_global_id"])
        if not drawing or not drawing.is_a("IfcAnnotation") or drawing.ObjectType != "DRAWING":
            raise RuntimeError(f"registered Drawing identity is missing: {row['drawing_name']}")
        pset = ifcopenshell.util.element.get_pset(drawing, "EPset_Drawing") or {}
        observed = {
            "drawing_name": drawing.Name,
            "target_view": pset.get("TargetView"),
            "scale": pset.get("Scale"),
            "shading_style": pset.get("CurrentShadingStyle"),
        }
        expected = {
            "drawing_name": row["drawing_name"],
            "target_view": row["target_view"],
            "scale": row["scale"],
            "shading_style": row["shading_style"],
        }
        if observed != expected:
            raise RuntimeError(f"registered Drawing settings drifted: {observed} != {expected}")

        reference = drawing_document(model, drawing)
        original_locations[drawing.GlobalId] = reference.Location or ""
        candidate_svg = candidate_dir / Path(row["svg_path"]).name
        reference.Location = str(candidate_svg.relative_to(PROJECT_ROOT))

        with bpy.context.temp_override(**drawing_operator_context()):
            result = bpy.ops.bim.activate_drawing(
                drawing=drawing.id(), should_view_from_camera=True
            )
            if result != {"FINISHED"}:
                raise RuntimeError(f"failed to activate {drawing.Name}: {result}")
            camera = bpy.context.scene.camera
            if not camera or camera.data.type != "ORTHO":
                raise RuntimeError(f"{drawing.Name}: Bonsai Drawing camera is not orthographic")

            props = tool.Drawing.get_document_props()
            props.should_use_underlay_cache = False
            props.should_use_linework_cache = False
            props.should_use_annotation_cache = False
            result = bpy.ops.bim.create_drawing(
                print_all=False, sync=False, open_viewer=False
            )
        if result != {"FINISHED"} or not candidate_svg.is_file():
            raise RuntimeError(f"Bonsai drawing refresh failed for {drawing.Name}: {result}")
        normalise_svg(candidate_svg)
        elevation_index = apply_official_elevation_index(
            candidate_svg, ELEVATION_INDEX_REGISTER
        )
        assets = local_svg_assets(candidate_svg)
        manifest: dict[str, Any] = {
            "schema_version": 2,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generator": "Bonsai native Drawing / bpy.ops.bim.create_drawing",
            "formal_ifc_sha256": formal_hash,
            "drawing_global_id": drawing.GlobalId,
            "drawing_name": drawing.Name,
            "target_view": pset["TargetView"],
            "scale": pset["Scale"],
            "shading_style": pset["CurrentShadingStyle"],
            "camera_type": camera.data.type,
            "camera_ortho_scale_m": float(camera.data.ortho_scale),
            "underlay_cache": props.should_use_underlay_cache,
            "linework_cache": props.should_use_linework_cache,
            "annotation_cache": props.should_use_annotation_cache,
            "texture_images_repaired": len(repaired),
            "unresolved_linked_texture_images": unresolved_linked,
            "unresolved_unlinked_texture_images": unresolved_unlinked,
            "source_svg_sha256": sha256(candidate_svg),
            "source_svg_bytes": candidate_svg.stat().st_size,
            "elevation_index": {
                "source": str(ELEVATION_INDEX_REGISTER.relative_to(PROJECT_ROOT)),
                "anchor_count": elevation_index["anchor_count"],
                "official_view_count": elevation_index["official_view_count"],
                "auxiliary_marker_count": elevation_index["auxiliary_marker_count"],
                "suppressed_ifc_drawing_marker_count": elevation_index["suppressed_ifc_drawing_marker_count"],
            },
            "linked_assets": assets,
            "formal_ifc_write_allowed": False,
        }
        expected_underlay = f"{drawing.Name}-underlay.png"
        underlay = next((asset for asset in assets if asset["href"] == expected_underlay), None)
        if underlay:
            manifest.update(
                {
                    "underlay_png_sha256": underlay["sha256"],
                    "underlay_width_px": underlay["width_px"],
                    "underlay_height_px": underlay["height_px"],
                }
            )
        manifest_candidate = candidate_dir / Path(row["manifest_path"]).name
        manifest_candidate.write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        reports.append(
            {
                "row": row,
                "drawing": drawing,
                "candidate_svg": candidate_svg,
                "candidate_manifest": manifest_candidate,
                "assets": assets,
            }
        )

    if sha256(ifc_path) != formal_hash:
        raise RuntimeError("formal IFC changed while refreshing Bonsai plan sources")

    for report in reports:
        row = report["row"]
        final_svg = PROJECT_ROOT / row["svg_path"]
        final_manifest = PROJECT_ROOT / row["manifest_path"]
        final_svg.parent.mkdir(parents=True, exist_ok=True)
        for asset in report["assets"]:
            os.replace(
                report["candidate_svg"].with_name(asset["href"]),
                final_svg.with_name(asset["href"]),
            )
        os.replace(report["candidate_svg"], final_svg)
        os.replace(report["candidate_manifest"], final_manifest)
        drawing = report["drawing"]
        drawing_document(model, drawing).Location = original_locations[drawing.GlobalId]

    if sha256(ifc_path) != formal_hash:
        raise RuntimeError("formal IFC changed during Bonsai source promotion")
    summary = {
        "mode": "read_only_bonsai_plan_source_refresh",
        "formal_ifc": str(ifc_path),
        "formal_ifc_sha256": formal_hash,
        "drawing_names": [report["row"]["drawing_name"] for report in reports],
        "drawing_count": len(reports),
        "disabled_unrelated_handlers": disabled_handlers,
        "formal_ifc_write_allowed": False,
        "formal_ifc_unchanged": True,
        "pass": True,
    }
    print("BONSAI_PLAN_REFRESH=" + json.dumps(summary, ensure_ascii=False), flush=True)
    # A normal wm.quit_blender() can crash in macOS OpenGL teardown after a
    # successful Bonsai underlay render. This process is disposable and the
    # formal IFC is never saved, so exit after flushing the completion marker.
    os._exit(0)


def run_after_window_initialises() -> None:
    try:
        main()
    except BaseException:
        traceback.print_exc()
        sys.stdout.flush()
        sys.stderr.flush()
        os._exit(1)


if __name__ == "__main__":
    if bpy.app.background:
        main()
    else:
        bpy.app.timers.register(run_after_window_initialises, first_interval=1.0)
