#!/usr/bin/env python3
"""Refresh Wall Plan.svg and its raster underlay inside the open Bonsai session."""

from __future__ import annotations

import hashlib
import json
import re
import struct
from datetime import datetime, timezone
from pathlib import Path

import bpy
import bonsai.tool as tool
import ifcopenshell.util.element


ROOT = Path(__file__).resolve().parents[2]
IFC_PATH = ROOT / "2504 GBTB Yanlord Zhuhai.ifc"
SOURCE_SVG = ROOT / "drawings/Wall Plan.svg"
UNDERLAY_PNG = ROOT / "drawings/Wall Plan-underlay.png"
SOURCE_MANIFEST = ROOT / "drawings/Wall Plan-source.json"
DRAWING_GLOBAL_ID = "33aMRH9An36RQi37lCJkbO"
UNDERLAY_REFERENCE = re.compile(
    r'<image\b[^>]*\bxlink:href="Wall Plan-underlay\.png"[^>]*/>'
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def png_dimensions(path: Path) -> tuple[int, int]:
    header = path.read_bytes()[:24]
    if len(header) != 24 or header[:8] != b"\x89PNG\r\n\x1a\n":
        raise RuntimeError(f"invalid PNG generated by Bonsai: {path}")
    return struct.unpack(">II", header[16:24])


def linked_materials(image: bpy.types.Image) -> list[str]:
    names: list[str] = []
    for material in bpy.data.materials:
        if not material.use_nodes or not material.node_tree:
            continue
        for node in material.node_tree.nodes:
            if getattr(node, "image", None) != image:
                continue
            if any(socket.links for socket in node.outputs):
                names.append(material.name)
    return sorted(set(names))


def repair_texture_paths() -> tuple[list[str], list[str], list[str]]:
    repaired: list[str] = []
    unresolved_linked: list[str] = []
    unresolved_unlinked: list[str] = []
    for image in bpy.data.images:
        if image.source != "FILE" or not image.filepath:
            continue
        if Path(bpy.path.abspath(image.filepath)).exists():
            continue
        raw = image.filepath.replace("\\", "/")
        candidate = Path("/Users/" + raw.split("/Users/", 1)[1]) if "/Users/" in raw else None
        if candidate and candidate.exists():
            image.filepath = str(candidate)
            image.reload()
            repaired.append(image.name)
            continue
        materials = linked_materials(image)
        target = unresolved_linked if materials else unresolved_unlinked
        target.append(f"{image.name}: {','.join(materials) if materials else 'unused'}")
    return repaired, unresolved_linked, unresolved_unlinked


def main() -> dict[str, object]:
    loaded_ifc = Path(tool.Ifc.get_path()).resolve()
    if loaded_ifc != IFC_PATH.resolve():
        raise RuntimeError(f"wrong IFC loaded in Bonsai: {loaded_ifc}")
    ifc_hash_before = sha256(IFC_PATH)
    model = tool.Ifc.get()
    drawing = model.by_guid(DRAWING_GLOBAL_ID)
    drawing_pset = ifcopenshell.util.element.get_pset(drawing, "EPset_Drawing")
    if drawing.Name != "Wall Plan" or drawing_pset.get("TargetView") != "PLAN_VIEW":
        raise RuntimeError("Wall Plan drawing identity or target view changed")

    repaired, unresolved_linked, unresolved_unlinked = repair_texture_paths()
    if unresolved_linked:
        raise RuntimeError(f"linked texture images are still missing: {unresolved_linked}")

    props = tool.Drawing.get_document_props()
    props.should_use_underlay_cache = False
    props.should_use_linework_cache = False
    props.should_use_annotation_cache = False
    bpy.ops.bim.activate_drawing(drawing=drawing.id(), should_view_from_camera=True)

    camera = bpy.context.scene.camera
    if not camera or camera.data.type != "ORTHO":
        raise RuntimeError("Wall Plan must use an orthographic drawing camera")
    perspectives = sorted(
        {
            area.spaces.active.region_3d.view_perspective
            for window in bpy.context.window_manager.windows
            for area in window.screen.areas
            if area.type == "VIEW_3D"
        }
    )
    if perspectives != ["CAMERA"]:
        raise RuntimeError(f"Wall Plan viewport is not locked to its camera: {perspectives}")

    result = bpy.ops.bim.create_drawing(sync=False, open_viewer=False)
    if result != {"FINISHED"}:
        raise RuntimeError(f"Bonsai drawing refresh failed: {result}")
    if sha256(IFC_PATH) != ifc_hash_before:
        raise RuntimeError("formal IFC changed while refreshing Wall Plan source")
    source = SOURCE_SVG.read_text(encoding="utf-8")
    normalized_source = "\n".join(line.rstrip() for line in source.splitlines())
    if source.endswith("\n"):
        normalized_source += "\n"
    if normalized_source != source:
        SOURCE_SVG.write_text(normalized_source, encoding="utf-8")
    if len(UNDERLAY_REFERENCE.findall(normalized_source)) != 1:
        raise RuntimeError("refreshed Wall Plan SVG does not reference exactly one underlay")

    width, height = png_dimensions(UNDERLAY_PNG)
    manifest = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "formal_ifc_sha256": ifc_hash_before,
        "drawing_global_id": drawing.GlobalId,
        "drawing_name": drawing.Name,
        "target_view": drawing_pset["TargetView"],
        "scale": drawing_pset["Scale"],
        "shading_style": drawing_pset["CurrentShadingStyle"],
        "camera_type": camera.data.type,
        "viewport_perspectives": perspectives,
        "underlay_cache": props.should_use_underlay_cache,
        "linework_cache": props.should_use_linework_cache,
        "annotation_cache": props.should_use_annotation_cache,
        "texture_images_repaired": len(repaired),
        "unresolved_linked_texture_images": unresolved_linked,
        "unresolved_unlinked_texture_images": unresolved_unlinked,
        "source_svg_sha256": sha256(SOURCE_SVG),
        "underlay_png_sha256": sha256(UNDERLAY_PNG),
        "underlay_width_px": width,
        "underlay_height_px": height,
    }
    SOURCE_MANIFEST.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(manifest, ensure_ascii=False))
    return manifest


if __name__ == "__main__":
    main()
